In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import numpy as np

a = np.ndarray(shape=(2,2), dtype = int)
a

array([[              0, 140734920546800],
       [              1,              -1]])

In [6]:
help(np.ndarray)

Help on class ndarray in module numpy:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any 

In [7]:
import numpy as np
a = np.ndarray((2,3))
a

array([[ 4.63939877e-308, -5.64938534e+036, -1.78409531e+046],
       [-4.32950182e-035, -8.72433218e-026, -1.57234264e-063]])

In [8]:
import numpy as np
a = np.ndarray((3,2), dtype= int)
a

array([[   9198723453795908, 5156903189229060492],
       [5298766577360225733, 4092864156735161052],
       [4231976415668524376, 3667252571916326280]])

In [9]:
import numpy as np
a = np.ndarray((2,3))
a

array([[ 4.63939877e-308, -5.64938534e+036, -1.78409531e+046],
       [-4.32950182e-035, -8.72433218e-026, -1.57234264e-063]])

In [10]:
np.ndarray?

Init signature: np.ndarray(self, /, *args, **kwargs)
Docstring:     
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object that can be interpreted as a numpy data type.
buffer : object exposing buffer int

In [11]:
import numpy as np
a = np.ndarray((2,2), dtype=int)
a

array([[            0, 2759737039712],
       [2759737039312, 2759737038352]])

In [12]:
print(a.shape)
print(a.ndim)
print(a.size)
print(a.itemsize)
print(a.dtype)
print(a.nbytes)

(2, 2)
2
4
8
int64
32


In [13]:
a.data

In [14]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, 

In [15]:
help(np.dtype)

Help on class dtype in module numpy:

class dtype(builtins.object)
 |  dtype(dtype, align=False, copy=False, [metadata])
 |
 |  Create a data type object.
 |
 |  A numpy array is homogeneous, and contains elements described by a
 |  dtype object. A dtype object can be constructed from different
 |  combinations of fundamental numeric types.
 |
 |  Parameters
 |  ----------
 |  dtype
 |      Object to be converted to a data type object.
 |  align : bool, optional
 |      Add padding to the fields to match what a C compiler would output
 |      for a similar C-struct. Can be ``True`` only if `obj` is a dictionary
 |      or a comma-separated string. If a struct dtype is being created,
 |      this also sets a sticky alignment flag ``isalignedstruct``.
 |  copy : bool, optional
 |      Make a new copy of the data-type object. If ``False``, the result
 |      may just be a reference to a built-in data-type object.
 |  metadata : dict, optional
 |      An optional dictionary with dtype meta

In [16]:
import numpy as np
a= np.array([1,2,3], dtype=int)
a

array([1, 2, 3])

In [17]:
type(a)

numpy.ndarray

In [18]:
print(a.shape)
print(a.ndim)
print(a.dtype)

(3,)
1
int64


In [19]:
print(a.size)
print(a.itemsize)
print(a.nbytes)

3
8
24


In [20]:
a.data

In [21]:
np.array{1,2,3} #오류

SyntaxError: invalid syntax (1698871585.py, line 1)

In [ ]:
np.array([1, 'py', 3.14])

array(['1', 'py', '3.14'], dtype='<U32')

In [ ]:
import numpy as np
unicode_array = np.array(['가나다', '라마바', '사아자'],dtype='<U32')
unicode_array

array(['가나다', '라마바', '사아자'], dtype='<U32')

In [ ]:
unicode_array = np.array(['가나다라마'*7, '라마바','사아자']dtype='<U32')
unicode_array

SyntaxError: invalid syntax. Perhaps you forgot a comma? (100997302.py, line 1)

In [ ]:
unicode_array = np.array(['가나다라마'*7, '라마바','사아자']dtype='<U64')
unicode_array

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1086490894.py, line 1)

In [ ]:
leng = np.array(['py','java','c'])
leng

array(['py', 'java', 'c'], dtype='<U4')

In [ ]:
a = np.array((1,2,3), dtype=float)
a

array([1., 2., 3.])

In [ ]:
b = np.array((1, 2.5 ,2))
b

array([1. , 2.5, 2. ])

In [ ]:
import numpy as np

print(np.arange(3))
print(np.arange(3,7))
print(np.arange(3,7,2))

[0 1 2]
[3 4 5 6]
[3 5]


In [ ]:
import numpy as np
print(np.arange(2.0))
print(np.arange(2.0, 6.5))
print(np.arange(2.0, 6.5, 0.8))

[0. 1.]
[2. 3. 4. 5. 6.]
[2.  2.8 3.6 4.4 5.2 6. ]


In [ ]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [3]:
np.arange(0,5,0.5, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
np.arange(-3,3,0.5,dtype=int)

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [24]:
import numpy as np

a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
np.reshape(a,(2,6))
#a.reshape(2.6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [26]:
np.reshape(a,(3,5))

ValueError: cannot reshape array of size 12 into shape (3,5)

In [27]:
b = np.array([1,2,3,4,5,6]).reshape(3,2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
np.reshape(b,(2,-1)) # np.reshape(b, ( 2,3))
np.reshape(b,(5,-1)) # ERROR
np.reshape(b,(6,-1)) # np.reshape(b, ( 6,1))

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
np.linspace(2.0, 3.0) #(2.0, 2.0, 50) => defult 50개

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [35]:
np.linspace(2.0 , 3.0, retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 np.float64(0.02040816326530612))

In [33]:
print((3-2) / (50-1))

0.02040816326530612


In [34]:
np.linspace(2.0, 3.0, endpoint=False, retstep=True)

(array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
        2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
        2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
        2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
        2.88, 2.9 , 2.92, 2.94, 2.96, 2.98]),
 np.float64(0.02))

In [36]:
print((3-2) / 50)

0.02


In [37]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), np.float64(0.25))

In [38]:
np.linspace(2.0, 3.0, num=5, endpoint=False, retstep=True)

(array([2. , 2.2, 2.4, 2.6, 2.8]), np.float64(0.2))

In [39]:
np.arange(0.1 , 0.4, 0.1)

array([0.1, 0.2, 0.3, 0.4])

In [40]:
np.arange(1,4,1) / 10.0

array([0.1, 0.2, 0.3])

In [41]:
np.linspace(0.1, 0.4, 3, endpoint=False)

array([0.1, 0.2, 0.3])

In [43]:
np.linspace(0.1, 0.4, 4)

array([0.1, 0.2, 0.3, 0.4])

In [45]:
import numpy as np

a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [46]:
a.dtype

dtype('float64')

In [47]:
np.zeros?

Docstring:
zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Al

In [48]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [49]:
b = np.zeros((2,1))
b

array([[0.],
       [0.]])

In [50]:
b.shape

(2, 1)

In [51]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [52]:
np.ones((2,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [53]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [54]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [55]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [56]:
a= np.eye(3,4,1)
a

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [57]:
b = np.eye(3,4,-1)
b

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [58]:
np.eye(3,4,-2)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.]])

In [59]:
np.full([2,3], 30)

array([[30, 30, 30],
       [30, 30, 30]])

In [60]:
np.full([2,3], (1,2,3))

array([[1, 2, 3],
       [1, 2, 3]])

In [61]:
np.full([2,3], (1,2)) #원소의 개수가 같아야 함

ValueError: could not broadcast input array from shape (2,) into shape (2,3)

In [62]:
np.full([3,4], range(4)) #np.full([3,4], [0,1,2,3])

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [64]:
np.full([4,3], fill_value=np.arange(4).reshape(4,1)) # reshape  때문에 세로로 모양에 맞추어 들어감

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [65]:
np.empty(3)

array([4.9e-324, 9.9e-324, 1.5e-323])

In [66]:
np.empty([2,2])

array([[0.0e+000, 4.9e-324],
       [9.9e-324, 1.5e-323]])

In [67]:
np.empty([2,3],dtype=int)

array([[25895968444448860, 23925768161198147, 32370111954616435],
       [16044279834148956, 18296268626395181, 27303364806049904]])

In [78]:
np.empty([3,2, 3], float)

array([[[            nan, 1.08646184e-311, 1.20552018e-320],
        [4.94065646e-324, 1.20552018e-320, 2.03060980e-321]],

       [[8.89318163e-321, 1.36232130e-311, 1.19761513e-320],
        [1.36232130e-311, 1.36350333e-311, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]]])

In [112]:
np.empty([3,2, 3], int)

array([[[25895968444448860, 23925768161198179, 32370111954616435],
        [16044279834148956, 18296268626395181, 27303364806049904]],

       [[21392493373358196, 30399714103066735, 31244212046397532],
        [30681189080760423, 34058815785402483, 30962724186357876]],

       [[32651616994721884, 14355696265920616, 21392493370277937],
        [33495917371981929, 32088598323331187, 11822344165523557]]])

In [70]:
import numpy as np

a = np.arange(8).reshape(2,4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [71]:
np.zeros_like(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [72]:
np.ones_like(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [73]:
np.full_like(a, 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [74]:
np.full_like(a, range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

In [141]:
import numpy as np
a = np.arange(3)
a

array([0, 1, 2])

In [142]:
print(a+2)
print(a-2)
print(a*2)
print(a/2)

[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


In [166]:
a = np.arange(1, 7).reshape(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [167]:
b = np.full_like(a, [1,2,3])
b

ValueError: could not broadcast input array from shape (3,) into shape (3,2)

In [168]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [146]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [130]:
b = np.arange(0.5 , 4, 1)
b

array([0.5, 1.5, 2.5, 3.5])

In [123]:
a +=b 

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [131]:
b += a
b

array([0.5, 2.5, 4.5, 6.5])

In [148]:
a = np.full((2,3), [ 1,2,3])
a

array([[1, 2, 3],
       [1, 2, 3]])

In [149]:
b = np.full((3,2), [2,1])
b

array([[2, 1],
       [2, 1],
       [2, 1]])

In [134]:
a@b

array([[12,  6],
       [12,  6]])

In [135]:
a.dot(b)

array([[12,  6],
       [12,  6]])

In [138]:
b.dot(a)

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])

In [150]:
import numpy as np
print(np.matmul(a,b))
print(np.matmul(b,a))

[[12  6]
 [12  6]]
[[3 6 9]
 [3 6 9]
 [3 6 9]]


In [152]:
a = np.array([[10,20],[5,8], [1,2]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [153]:
a.sum()

np.int64(46)

In [154]:
a.sum(axis=0)

array([16, 30])

In [155]:
a.sum(axis=1)

array([30, 13,  3])

In [156]:
import numpy as np

print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

46
[16 30]
[30 13  3]


In [157]:
a = np.array([[3,5,8], [1,2,3]])
a

array([[3, 5, 8],
       [1, 2, 3]])

In [158]:
a.cumsum() #차원을 펼져서 계산

array([ 3,  8, 16, 17, 19, 22])

In [159]:
a.cumsum(axis=0)

array([[ 3,  5,  8],
       [ 4,  7, 11]])

In [160]:
a.cumsum(axis=1)

array([[ 3,  8, 16],
       [ 1,  3,  6]])

In [169]:
import numpy as np
a= np.array([1,4,9])
np.sqrt(a)

array([1., 2., 3.])

In [170]:
np.log(a)

array([0.        , 1.38629436, 2.19722458])

In [171]:
import numpy as np

a =np.array([1,4,9])
a

array([1, 4, 9])

In [172]:
b = np.full_like(a, 2)
b

array([2, 2, 2])

In [173]:
np.add(a,b)

array([ 3,  6, 11])

In [174]:
np.divide(a,b)

array([0.5, 2. , 4.5])

In [175]:
np.power(a,b)

array([ 1, 16, 81])

In [176]:
import numpy as np

a = np.power(np.arange(10),2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [177]:
print(a[3])
print(a[-2])

9
64


In [178]:
print(a[1:4])
print(a[-5:-1])

[1 4 9]
[25 36 49 64]


In [179]:
print(a[8:2:-1])
print(a[-1:-7:-1])

[64 49 36 25 16  9]
[81 64 49 36 25 16]


In [180]:
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [181]:
a[::-2]

array([81, 49, 25,  9,  1])

In [182]:
a[2:5] = -100
a

array([   0,    1, -100, -100, -100,   25,   36,   49,   64,   81])

In [183]:
a[2: 5] = [-5, -5, -5]
a

array([ 0,  1, -5, -5, -5, 25, 36, 49, 64, 81])

In [184]:
a[2: 5] = [-5, -5]
a

ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [185]:
a[2: 6] = [-5, -5]
a

ValueError: could not broadcast input array from shape (2,) into shape (4,)

In [186]:
a[2:5] = -10
a

array([  0,   1, -10, -10, -10,  25,  36,  49,  64,  81])

In [187]:
b = np.array([5] * 10)
b

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [188]:
b[::2] = -10
b

array([-10,   5, -10,   5, -10,   5, -10,   5, -10,   5])

In [189]:
b[::2] = np.arange(5)
b

array([0, 5, 1, 5, 2, 5, 3, 5, 4, 5])

In [190]:
a = np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [191]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [192]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [193]:
a[-2, :]

array([18, 19, 20, 21, 22, 23])

In [194]:
a[-2,]

array([18, 19, 20, 21, 22, 23])

In [195]:
a[2:4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [196]:
a[1:5:2]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [198]:
a[,1]

SyntaxError: invalid syntax (3819423678.py, line 1)

In [199]:
a[:, 1]

array([ 1,  7, 13, 19, 25])

In [200]:
a[:, 1:6]

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

In [201]:
a[:, ::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [203]:
a[::2]

array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17],
       [24, 25, 26, 27, 28, 29]])

In [204]:
a[2,4]

np.int64(16)

In [205]:
a[2][4]

np.int64(16)

In [206]:
a[1:3, 2:5]

array([[ 8,  9, 10],
       [14, 15, 16]])

In [207]:
a[:, :]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [208]:
a[:,]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [209]:
a[:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [210]:
a[::-1, ::-1]

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [211]:
a[:-1, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

In [213]:
a= np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [214]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [215]:
a[:,1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [216]:
a[:,1,1]

array([ 5, 17])

In [217]:
a[:,:,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [218]:
a[...,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [219]:
a[1,...,1]

array([13, 17, 21])

In [220]:
a[0,...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [221]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [222]:
a[:, :,2:]

array([[[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[14, 15],
        [18, 19],
        [22, 23]]])

In [223]:
a[:,:,3:]

array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])

In [224]:
a[:,:,3]

array([[ 3,  7, 11],
       [15, 19, 23]])

In [225]:
a= np.arange(12).reshape(2,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [226]:
b= a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [227]:
b[0] = 100
b

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [228]:
a

array([[[100,   1],
        [  2,   3],
        [  4,   5]],

       [[  6,   7],
        [  8,   9],
        [ 10,  11]]])

In [229]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [230]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [231]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [232]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [233]:
np.transpose(a,(0,1))

array([[1, 2, 3],
       [4, 5, 6]])

In [234]:
np.transpose(a,(1,0))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [235]:
b = np.arange(1,13).reshape(3,2,2)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [236]:
b.T

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [237]:
np.transpose(b,(0,1,2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [238]:
np.transpose(b,(2,1,0))

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [239]:
np.transpose(b,(0,2,1))

array([[[ 1,  3],
        [ 2,  4]],

       [[ 5,  7],
        [ 6,  8]],

       [[ 9, 11],
        [10, 12]]])

In [240]:
c = np.arange(1,13).reshape(2,2,3)
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [241]:
c.transpose(1,2,0)

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [242]:
np.transpose(c,(1,2,0))

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [243]:
np.transpose(c)

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])