In [7]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [9]:
import numpy as np
x = np.array([[7,8,9]])
x

array([[7, 8, 9]])

In [12]:
y = np.swapaxes(x, 0,1)
y

array([[10],
       [ 8],
       [ 9]])

In [14]:
y = np.swapaxes(x, 1, 0)
y

array([[10],
       [ 8],
       [ 9]])

In [17]:
y[0,0] = 10
x

array([[10,  8,  9]])

In [18]:
x = np.array(np.arange(8).reshape(2,2,2))
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [19]:
np.swapaxes(x, 0,2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [20]:
np.transpose(x, (2,1,0))

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [21]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [22]:
v = org.view()
v

array([0, 1, 2, 3, 4])

In [23]:
v[2] = 200
v

array([  0,   1, 200,   3,   4])

In [24]:
org

array([  0,   1, 200,   3,   4])

In [25]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [26]:
c = org.copy()
c

array([0, 1, 2, 3, 4])

In [27]:
c[2] = 200
c

array([  0,   1, 200,   3,   4])

In [28]:
org

array([0, 1, 2, 3, 4])

In [29]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [30]:
y = x.reshape(2,3)
y

array([[0, 1, 2],
       [3, 4, 5]])

In [31]:
print(x.base)

None


In [32]:
y.base

array([0, 1, 2, 3, 4, 5])

In [33]:
y

array([[0, 1, 2],
       [3, 4, 5]])

In [34]:
y.base

array([0, 1, 2, 3, 4, 5])

In [35]:
z = y.transpose()
z.base

array([0, 1, 2, 3, 4, 5])

In [36]:
c = z.copy()
print(c.base)

None


In [37]:
lst = list(range(8))
lst

[0, 1, 2, 3, 4, 5, 6, 7]

In [38]:
lst[3:5] = [30,40,50]
lst

[0, 1, 2, 30, 40, 50, 5, 6, 7]

In [39]:
x = np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [40]:
x[3:5] = [30,40]
x

array([ 0,  1,  2, 30, 40,  5,  6,  7])

In [41]:
x[3:5] = [30,40,50]
x

ValueError: could not broadcast input array from shape (3,) into shape (2,)

In [42]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
b=a
b is a

True

In [45]:
print(id(a))
print(id(b))

1521981418512
1521981418512


In [46]:
print(a.base)
print(b.base)

None
None


In [47]:
b[0,0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [48]:
c = a.copy()
c

array([[100,   2,   3],
       [  4,   5,   6]])

In [49]:
print(id(a))
print(id(c))

1521981418512
1521981423408


In [50]:
print(c.base)

None


In [51]:
v = a.reshape(3,2)
v

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [52]:
print(id(a))
print(id(v))

1521981418512
1521981225168


In [53]:
v[0,1] = 200
a

array([[100, 200,   3],
       [  4,   5,   6]])

In [54]:
v.base

array([[100, 200,   3],
       [  4,   5,   6]])

In [55]:
a = np.array([3,4,5])
b = np.array([8,7,6])
a+b

array([11, 11, 11])

In [56]:
a = np.array([3,4,5,7])
b = np.array([8,7,6])
a*b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [57]:
from numpy import arange
x = arange(1, 10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
y = arange(-1, 2)
y

array([-1,  0,  1])

In [59]:
x*y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [60]:
x+y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [61]:
from numpy import arange
x = arange(1, 10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
y = arange(3, 10, 3).reshape(3,1)
y

array([[3],
       [6],
       [9]])

In [63]:
np.set_printoptions(precision=2)


In [64]:
x / y

array([[0.33, 0.67, 1.  ],
       [0.67, 0.83, 1.  ],
       [0.78, 0.89, 1.  ]])

In [65]:
x - y

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [66]:
from numpy import arange

x = arange(1,4)
x

array([1, 2, 3])

In [67]:
y = arange(1,4).reshape(3,1)
y

array([[1],
       [2],
       [3]])

In [68]:
x*y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [69]:
x/y

array([[1.  , 2.  , 3.  ],
       [0.5 , 1.  , 1.5 ],
       [0.33, 0.67, 1.  ]])

In [70]:
from numpy import arange
x = arange(0,10,3).reshape(4,1)
x

array([[0],
       [3],
       [6],
       [9]])

In [71]:
y = arange(1,3)
y

array([1, 2])

In [72]:
x*y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [73]:
x+y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [75]:
import numpy as np
from numpy import array
x = array([0,10,20,30])
x

array([ 0, 10, 20, 30])

In [76]:
np.newaxis is None

True

In [77]:
a = x[None, :]

In [78]:
a = x[np.newaxis, :]
a

array([[ 0, 10, 20, 30]])

In [79]:
a = x[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [80]:
a=x[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [81]:
a.shape

(4, 1)

In [82]:
a = x[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [83]:
from numpy import array
b = array([1,2,3])
b

array([1, 2, 3])

In [84]:
b

array([1, 2, 3])

In [85]:
a+b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [86]:
a*b

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [87]:
x = np. arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
print(x[1])
print(x[:5])


1
[0 1 2 3 4]


In [89]:
print(x[[2]])
print(x[[2,3]])

[2]
[2 3]


In [90]:
x[[2,3,5,8]]

array([2, 3, 5, 8])

In [91]:
x[np.array([5,3,-4, 8])]

array([5, 3, 6, 8])

In [92]:
from numpy import arange
x= arange(56).reshape(7,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [93]:
x[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [94]:
x[0,1]

np.int64(1)

In [95]:
x[:,2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [96]:
x[,2:8]

SyntaxError: invalid syntax (1821174162.py, line 1)

In [97]:
x[[0],[1]]

array([1])

In [98]:
x[[0,1]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [99]:
x[:,[5,4]]

array([[ 5,  4],
       [13, 12],
       [21, 20],
       [29, 28],
       [37, 36],
       [45, 44],
       [53, 52]])

In [100]:
x[[1,3]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [101]:
x[[1,3], :]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [102]:
from numpy import array

x[array([0,2,4]), array([0,1])]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [103]:
from numpy import arange

x= arange(56).reshape(7,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [104]:
x[np.array([0,2,4]),1]

array([ 1, 17, 33])

In [105]:
print(x[0,1])
print(x[2,1])
print(x[4,1])

1
17
33


In [106]:
x[array([0,2,4]), : 2]

array([[ 0,  1],
       [16, 17],
       [32, 33]])

In [112]:
from numpy import arange

a = arange(40).reshape(5,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [113]:
a[2:4, 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [114]:
a[arange(2,4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [116]:
from numpy import arange

a =arange(40).reshape(5,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [117]:
a[arange(2,4)][:,[1,0]]

array([[17, 16],
       [25, 24]])

In [118]:
a[arange(2,5)][:,[1,0,3,5]]


array([[17, 16, 19, 21],
       [25, 24, 27, 29],
       [33, 32, 35, 37]])

In [119]:
a[arange(2,5)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [120]:
a[arange(2,5)][:, arange(-1, -8, -1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])

## 5주차 수업

In [121]:
import numpy as np
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [122]:
b = np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [123]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [125]:
import numpy as np

x =np.array([1,2,3])
y = np.array([5,6,7])
np.vstack((x,y))

array([[1, 2, 3],
       [5, 6, 7]])

In [126]:
import numpy as np
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [127]:
b = np.arange(10,19).reshape(3,3)

In [128]:
np.hstack((a,b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [129]:
np.hstack((np.arange(3), np.arange(10, 15)))

array([ 0,  1,  2, 10, 11, 12, 13, 14])

In [130]:
x = np.array([1,2,3])
y = np.array([10,20,30])
np.column_stack((x,y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [131]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [132]:
x = np.array([1,2,3])
y = np.array([10,20,30])
np.column_stack((x[:, np.newaxis], y[:, np.newaxis]))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [133]:
np.hstack((x,y))

array([ 1,  2,  3, 10, 20, 30])

In [134]:
np.column_stack == np.hstack

False

In [139]:
import numpy as np
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [140]:
b = np.arange(10,22).reshape(4,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [143]:
np.row_stack((a,b))

C:\Users\109-1\AppData\Local\Temp\ipykernel_6300\1307586492.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [144]:
import numpy as np

a = np.array([1,2])
b = np.array([3,4])
c = np.array([5,6])

In [145]:
np.concatenate((a,b,c))

array([1, 2, 3, 4, 5, 6])

In [147]:
np.concatenate((a,b,c), axis=0)

array([1, 2, 3, 4, 5, 6])

In [149]:
np.concatenate((a,b,c), axis = None)

array([1, 2, 3, 4, 5, 6])

In [150]:
import numpy as np
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [152]:
y = np.arange(10,16).reshape(2,3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [153]:
z = np.arange(20, 24).reshape(2,2)

In [154]:
np.concatenate((x,y))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [155]:
np.concatenate((x,y), axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [156]:
np.concatenate((x,y,z), axis=1)


array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [158]:
np.concatenate((x,y), axis=None)

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

In [159]:
import numpy as np

a = np.array([1,2,3])
a

array([1, 2, 3])

In [160]:
b = np.array([4,5,6])
b

array([4, 5, 6])

In [161]:
np.stack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [162]:
np.stack((a,b), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [164]:
np.stack((a,b), axis=-1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [165]:
np.arange(1, 19).reshape(3,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [166]:
np.arange(16).reshape(2,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [167]:
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [168]:
y = np.arange(10,16).reshape(2,3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [171]:
z = np.arange(20,26).reshape(2,3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [172]:
ax0 = np.stack((x,y,z), axis=0)
ax0

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]]])

In [173]:
ax0.shape

(3, 2, 3)

In [174]:
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [175]:
y = np.arange(10,16).reshape(2,3)

In [176]:
z = np.arange(20, 26).reshape(2,3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [177]:
ax1 = np.stack((x,y,z), axis=1)
ax1

array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]],

       [[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25]]])

In [178]:
ax1.shape

(2, 3, 3)

In [179]:
ax2 = np.stack((x,y,z),axis=2)
ax2

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [180]:
ax2.shape

(2, 3, 3)

In [183]:
print('np.stack((x, y, z), axis=0)')
print(np.stack((x, y, z), axis=0))
print('np.stack((x, y, z), axis=1)')
print(np.stack((x, y, z), axis=1))
print('np.stack((x, y, z), axis=2)')
print(np.stack((x, y, z), axis=2))

np.stack((x, y, z), axis=0)
[[[ 0  1  2]
  [ 3  4  5]]

 [[10 11 12]
  [13 14 15]]

 [[20 21 22]
  [23 24 25]]]
np.stack((x, y, z), axis=1)
[[[ 0  1  2]
  [10 11 12]
  [20 21 22]]

 [[ 3  4  5]
  [13 14 15]
  [23 24 25]]]
np.stack((x, y, z), axis=2)
[[[ 0 10 20]
  [ 1 11 21]
  [ 2 12 22]]

 [[ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]]]


In [184]:
x


array([[0, 1, 2],
       [3, 4, 5]])

In [185]:
x[:,:,np.newaxis]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [186]:
np.expand_dims(x, axis=2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [187]:
y

array([[10, 11, 12],
       [13, 14, 15]])

In [188]:
y[:,:,np.newaxis]

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [189]:
np.expand_dims(y,axis=2)

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [190]:
z

array([[20, 21, 22],
       [23, 24, 25]])

In [191]:
z[:,:,np.newaxis]

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [192]:
np.expand_dims(z, axis=2)

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [193]:
np.stack((x,y,z), axis=2)

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [197]:
np.hstack((a, np.expand_dims(c, axis=1)))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [198]:
np.column_stack((a,c))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [199]:
import numpy as np
a= np.arange(1, 13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [200]:
b = np.arange(1,5)
b

array([1, 2, 3, 4])

In [201]:
np.row_stack((a,b))

C:\Users\109-1\AppData\Local\Temp\ipykernel_6300\1307586492.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [202]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [203]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

In [204]:
np.c_[a,b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [205]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [206]:
x = np. array([[1,2,3]])
y = np.array([[4,5,6]])

In [207]:
np.c_[x,y]

array([[1, 2, 3, 4, 5, 6]])

In [208]:
np.column_stack((x,y))

array([[1, 2, 3, 4, 5, 6]])

In [209]:
np.c_[x,10,20,y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [210]:
np.column_stack((x, 10, 20, y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [211]:
import numpy as np
a = np. array ([1,2,3])
b = np.array([4,5,6])

In [212]:
np.r_[a,b]

array([1, 2, 3, 4, 5, 6])

In [213]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [214]:
np.row_stack((a,b))

C:\Users\109-1\AppData\Local\Temp\ipykernel_6300\1307586492.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))


array([[1, 2, 3],
       [4, 5, 6]])

In [215]:
np.r_[a,0,0,b]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [216]:
np.r_[3:10:3, [0*2],5,6]

array([3, 6, 9, 0, 5, 6])

In [217]:
np.r_[-1:1:6j, [0]*2,5,6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])

In [218]:
np.linspace(-1, 1, 6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

In [236]:
a= np.array([[0,1,2], [3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [237]:
np.r_[a,a,a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [238]:
np.r_['0', a,a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [239]:
np.r_['-1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [240]:
np.r_['1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [241]:
np.r_['0, 2', a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [242]:
np.r_['0, 2', [1,2,3], [4,5,6]]

array([[1, 2, 3],
       [4, 5, 6]])

In [243]:
np.r_['0, 3', [ 1,2,3], [4,5,6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [244]:
arr = np.array([1,2,3])
print(arr[:,np.newaxis])
print(arr[np.newaxis, :])

[[1]
 [2]
 [3]]
[[1 2 3]]


In [245]:
np.expand_dims(arr, 0)

array([[1, 2, 3]])

In [246]:
np.expand_dims(arr,1)

array([[1],
       [2],
       [3]])

In [247]:
np.expand_dims(np.array([1,2,3]), axis=(1,2))

array([[[1]],

       [[2]],

       [[3]]])

In [248]:
np.expand_dims(np.array([4,5,6]), axis=(1,2))

array([[[4]],

       [[5]],

       [[6]]])

In [249]:
np.r_['0,3,0',[1,2,3], [4,5,6]]

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]]])

In [250]:
np.r_['0,3,0',[1,2,3], [4,5,6]].shape  

(6, 1, 1)

In [251]:
np.r_['0,3,1',[1,2,3], [4,5,6]]

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [252]:
print(np.expand_dims(np.array([1,2,3]), axis=(0,2)))
print(np.expand_dims(np.array([4,5,6]), axis=(0,2)))

[[[1]
  [2]
  [3]]]
[[[4]
  [5]
  [6]]]


In [253]:
np.r_['0,3,1', [1,2,3], [4,5,6]].shape

(2, 3, 1)

In [254]:
np.r_['0,3,2', [1,2,3], [4,5,6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [255]:
print(np.expand_dims(np.array([1,2,3]), axis=(0,1)))
print(np.expand_dims(np.array([4,5,6]), axis=(0,1)))

[[[1 2 3]]]
[[[4 5 6]]]


In [257]:
np.r_['0,3,2', [1,2,3], [4,5,6]].shape

(2, 1, 3)

In [258]:
print(np.r_[[[1,2,3]], [[4,5,6]]])
np.r_['r', [[1,2,3]], [[4,5,6]]]

[[1 2 3]
 [4 5 6]]


matrix([[1, 2, 3],
        [4, 5, 6]])

In [259]:
np.r_['c', [[1,2,3]], [[4,5,6]]]

matrix([[1, 2, 3],
        [4, 5, 6]])

In [261]:
print(np.r_[[1,2,3],[4,5,6]])

np.r_['r', [1,2,3], [4,5,6]]

[1 2 3 4 5 6]


matrix([[1, 2, 3, 4, 5, 6]])

In [262]:
print(np.r_[[1,2,3],[4,5,6]])

np.r_['c', [1,2,3], [4,5,6]]

[1 2 3 4 5 6]


matrix([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [263]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

In [264]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [265]:
np.r_[a,b]

array([1, 2, 3, 4, 5, 6])

In [266]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [267]:
np.c_[a,b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [268]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [269]:
np.row_stack((a,b))

C:\Users\109-1\AppData\Local\Temp\ipykernel_6300\1307586492.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))


array([[1, 2, 3],
       [4, 5, 6]])

In [270]:
np.r_[a[np.newaxis, :], b[np.newaxis, :]]

array([[1, 2, 3],
       [4, 5, 6]])

In [271]:
np.concatenate((a[np.newaxis, :], b[np.newaxis, :]))

array([[1, 2, 3],
       [4, 5, 6]])

In [272]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [273]:
np.hstack((a[:, np.newaxis], b[:, np.newaxis]))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [274]:
np.c_[a,b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [276]:
np.r_['1,2,0',a,b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [275]:
np.concatenate(((a[:,np.newaxis], b[:,np.newaxis])), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [278]:
import numpy as np

x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [279]:
s = np.split(x,3)
s

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [280]:
np.split(y, [2,3,4,6])

[array([[4, 5, 6]]),
 array([], shape=(0, 3), dtype=int64),
 array([], shape=(0, 3), dtype=int64),
 array([], shape=(0, 3), dtype=int64),
 array([], shape=(0, 3), dtype=int64)]

In [282]:
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [283]:
np.split(x, [2,6])

[array([1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [285]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [286]:
a= np.arange(24). reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [287]:
np.split(a, 3, axis=1)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [288]:
np.split(a, 4, axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [15, 16, 17]]),
 array([[ 6,  7,  8],
        [18, 19, 20]]),
 array([[ 9, 10, 11],
        [21, 22, 23]])]

In [289]:
b = np.arange(24).reshape(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [290]:
np.split(b,3, axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [291]:
np.split(b, [2,4,6], axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([], shape=(0, 4), dtype=int64)]

In [292]:
a = np.arange(24).reshape(2,12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [293]:
np.split(a, [ 3,5,7], axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6],
        [17, 18]]),
 array([[ 7,  8,  9, 10, 11],
        [19, 20, 21, 22, 23]])]

In [294]:
b = np.arange(24).reshape(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [295]:
np.split(b,3, axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [296]:
a= np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [297]:
np. hsplit(a,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [298]:
np.hsplit(a, [2,5])

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

In [299]:
a= np.arange(24).reshape(2,12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [300]:
np.hsplit(a,(3,5,8))

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6,  7],
        [17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [301]:
a[ :, 8:]

array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])

In [302]:
a[:, :3]

array([[ 0,  1,  2],
       [12, 13, 14]])

In [303]:
a= np.arange(18).reshape(6,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [304]:
np.vsplit(a,3)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [305]:
np.vsplit(a,4)

ValueError: array split does not result in an equal division

In [306]:
np.vsplit(a, (1,4,6))

[array([[0, 1, 2]]),
 array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]]),
 array([], shape=(0, 3), dtype=int64)]

In [307]:
a[:1,:]

array([[0, 1, 2]])

In [308]:
a[4:6,:]

array([[12, 13, 14],
       [15, 16, 17]])

In [309]:
a[6:, :]

array([], shape=(0, 3), dtype=int64)

In [310]:
x = np.arange(32).reshape(4,4,2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [311]:
np.hsplit(x,2)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

In [313]:
np.split(x,2,axis=1)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

In [314]:
x = np.arange(32).reshape(4,4,2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [315]:
np.hsplit(x,[1,3])

[array([[[ 0,  1]],
 
        [[ 8,  9]],
 
        [[16, 17]],
 
        [[24, 25]]]),
 array([[[ 2,  3],
         [ 4,  5]],
 
        [[10, 11],
         [12, 13]],
 
        [[18, 19],
         [20, 21]],
 
        [[26, 27],
         [28, 29]]]),
 array([[[ 6,  7]],
 
        [[14, 15]],
 
        [[22, 23]],
 
        [[30, 31]]])]

In [316]:
np.split(x,2, axis=0)

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [317]:
np.vsplit(x,2)

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [318]:
np.vsplit(x,[1,3])

[array([[[0, 1],
         [2, 3],
         [4, 5],
         [6, 7]]]),
 array([[[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]],
 
        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]]]),
 array([[[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [319]:
x = np. arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [320]:
np.array_split(x,2)

[array([0., 1., 2., 3., 4.]), array([5., 6., 7., 8.])]

In [321]:
np.array_split(x,3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [322]:
np.array_split(x,4)

[array([0., 1., 2.]), array([3., 4.]), array([5., 6.]), array([7., 8.])]

In [323]:
np.array_split(x,5)

[array([0., 1.]),
 array([2., 3.]),
 array([4., 5.]),
 array([6., 7.]),
 array([8.])]

In [324]:
np.array_split(x,[2,4,8])

[array([0., 1.]), array([2., 3.]), array([4., 5., 6., 7.]), array([8.])]

In [327]:
import numpy as np
a= np.arange(35).reshape(7,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [328]:
np.array_split(a, 2, axis=0)

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]])]

In [330]:
np.array_split(a,2,axis=1)

[array([[ 0,  1,  2],
        [ 5,  6,  7],
        [10, 11, 12],
        [15, 16, 17],
        [20, 21, 22],
        [25, 26, 27],
        [30, 31, 32]]),
 array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19],
        [23, 24],
        [28, 29],
        [33, 34]])]

In [332]:
np.array_split(a,[2,4],axis=0)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]])]

In [333]:
np.array_split(a,[2,4],axis=1)

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21],
        [25, 26],
        [30, 31]]),
 array([[ 2,  3],
        [ 7,  8],
        [12, 13],
        [17, 18],
        [22, 23],
        [27, 28],
        [32, 33]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24],
        [29],
        [34]])]

In [334]:
import numpy as np

x = np.arange(24).reshape(2,2,6)
x

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [335]:
np.array_split(x, 4, axis=2)

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]),
 array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]),
 array([[[ 4],
         [10]],
 
        [[16],
         [22]]]),
 array([[[ 5],
         [11]],
 
        [[17],
         [23]]])]

In [336]:
x= np.arange(24).reshape(2,2,6)
x

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [337]:
np.dsplit(x,2)

[array([[[ 0,  1,  2],
         [ 6,  7,  8]],
 
        [[12, 13, 14],
         [18, 19, 20]]]),
 array([[[ 3,  4,  5],
         [ 9, 10, 11]],
 
        [[15, 16, 17],
         [21, 22, 23]]])]

In [338]:
np.split(x, 2, axis=2)

[array([[[ 0,  1,  2],
         [ 6,  7,  8]],
 
        [[12, 13, 14],
         [18, 19, 20]]]),
 array([[[ 3,  4,  5],
         [ 9, 10, 11]],
 
        [[15, 16, 17],
         [21, 22, 23]]])]

In [339]:
x = np.arange(24).reshape(2,2,6)
x

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [340]:
np.dsplit(x, [2,4,5])

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]),
 array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]),
 array([[[ 4],
         [10]],
 
        [[16],
         [22]]]),
 array([[[ 5],
         [11]],
 
        [[17],
         [23]]])]

In [341]:
rg = np.random.default_rng(12345)
rg

Generator(PCG64) at 0x1625D3D12A0

In [342]:
r = rg.random()
r

0.22733602246716966

In [343]:
rg.random(5)

array([0.32, 0.8 , 0.68, 0.39, 0.33])

In [344]:
rg.random((4,3))

array([[0.6 , 0.19, 0.67],
       [0.94, 0.25, 0.95],
       [0.67, 0.1 , 0.44],
       [0.89, 0.7 , 0.33]])

In [345]:
rg = np.random.default_rng(12345)
r = rg.integers(low=0, high=10, size=3)
r
    

array([6, 2, 7])

In [346]:
rg.integers(1,7,(3,4))

array([[2, 2, 5, 4],
       [5, 6, 3, 6],
       [2, 4, 4, 2]])

In [347]:
rg = np.random.default_rng(seed=42)
rg.standard_normal(10)

array([ 0.3 , -1.04,  0.75,  0.94, -1.95, -1.3 ,  0.13, -0.32, -0.02,
       -0.85])

In [348]:
rg.standard_normal((4,3))

array([[ 0.88,  0.78,  0.07],
       [ 1.13,  0.47, -0.86],
       [ 0.37, -0.96,  0.88],
       [-0.05, -0.18, -0.68]])